language: go
go:
  - 1.14
install:
  - go get https://github.com/gohugoio/hugo/tree/release-0.68.0
script:
  - hugo
deploy:
  local_dir: public
  repo: cbgoodman/cbgoodman.github.io
  target_branch: master
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  email: cgoodman@niu.edu
  name: "Christopher Goodman"
  on:
    branch: master
