language: go
go:
  - 1.14
install:
  #- go get github.com/gohugoio/hugo
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.83.1/hugo_0.83.1_Linux-64bit.deb
  - sudo dpkg -i hugo_0.83.1_Linux-64bit.deb
script:
  - hugo
deploy:
  local_dir: public
  repo: cbgoodman/cbgoodman.github.io
  target_branch: master
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  email: cgoodman@niu.edu
  name: "Christopher Goodman"
  on:
    branch: master
