language: go
go:
  - 1.12
install:
  - go get github.com/gohugoio/hugo
script:
  - hugo version
  - hugo
deploy:
  local_dir: public
  repo: cbgoodman/cbgoodman.github.io
  target_branch: master
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  email: cgoodman@niu.edu
  name: "Christopher Goodman"
  on:
    branch: master
