language: go
go:
  - master
install:
  - go get https://github.com/gohugoio/hugo
script:
  - hugo
deploy:
  local_dir: public
  repo: cbgoodman/cbgoodman.github.io
  target_branch: master
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  email: cbgoodman@unomaha.edu
  name: "Christopher Goodman"
  on:
    branch: master
